@extends('front.layouts.interna')

@section('content')
@include('front.articles.assets.section-intro',array('title'=>'Economía','img'=>'/img/test/keiser.jpg','txt'=>'Keiser report – Mercados, finanzas, escándalos. Keiser report es una mirada a los escándalos detrás de los titulares financieros globales. Sean las colusiones entre Wall Street y el Congreso o la última oleada de delitos bancarios, las falsas estadísticas económicas gubernamentales o maquinaciones bursátiles, nada escapa al ojo de Max Keiser. Ex agente de valores, inventor de una tecnología virtual y cofundador de la bolsa de valores de Hollywood, Keiser ofrece el resumen de lo que pasa verdaderamente en la economía global, con la aportación de la copresentadora Stacy Herbert e invitados de varias partes del mundo.'))

@include('front.articles.assets.content-of-list',array('title'=>'Soberanía Argentina','img'=>'/img/test/malvinas.jpg','url'=>'/economia/malvinas','txt'=>'Hoy se celebrará una reunión del Consejo OTAN-Rusia a nivel de embajadores. Hoy se celebrará una reunión del Consejo OTAN-Rusia a nivel de embajadores. Hoy se celebrará una reunión del Consejo OTAN-Rusia a nivel de embajadores. Hoy se celebrará una reunión del Consejo OTAN-Rusia a nivel de embajadores.'))
@include('front.articles.assets.content-of-list',array('title'=>'Soberanía Argentina','img'=>'/img/test/malvinas.jpg','url'=>'/economia/malvinas','txt'=>'Hoy se celebrará una reunión del Consejo OTAN-Rusia a nivel de embajadores. Hoy se celebrará una reunión del Consejo OTAN-Rusia a nivel de embajadores. Hoy se celebrará una reunión del Consejo OTAN-Rusia a nivel de embajadores. Hoy se celebrará una reunión del Consejo OTAN-Rusia a nivel de embajadores.'))
@include('front.articles.assets.content-of-list',array('title'=>'Soberanía Argentina','img'=>'/img/test/malvinas.jpg','url'=>'/economia/malvinas','txt'=>'Hoy se celebrará una reunión del Consejo OTAN-Rusia a nivel de embajadores. Hoy se celebrará una reunión del Consejo OTAN-Rusia a nivel de embajadores. Hoy se celebrará una reunión del Consejo OTAN-Rusia a nivel de embajadores. Hoy se celebrará una reunión del Consejo OTAN-Rusia a nivel de embajadores.'))
@include('front.articles.assets.content-of-list',array('title'=>'Soberanía Argentina','img'=>'/img/test/malvinas.jpg','url'=>'/economia/malvinas','txt'=>'Hoy se celebrará una reunión del Consejo OTAN-Rusia a nivel de embajadores. Hoy se celebrará una reunión del Consejo OTAN-Rusia a nivel de embajadores. Hoy se celebrará una reunión del Consejo OTAN-Rusia a nivel de embajadores. Hoy se celebrará una reunión del Consejo OTAN-Rusia a nivel de embajadores.'))
@include('front.articles.assets.content-of-list',array('title'=>'Soberanía Argentina','img'=>'/img/test/malvinas.jpg','url'=>'/economia/malvinas','txt'=>'Hoy se celebrará una reunión del Consejo OTAN-Rusia a nivel de embajadores. Hoy se celebrará una reunión del Consejo OTAN-Rusia a nivel de embajadores. Hoy se celebrará una reunión del Consejo OTAN-Rusia a nivel de embajadores. Hoy se celebrará una reunión del Consejo OTAN-Rusia a nivel de embajadores.'))
@include('front.articles.assets.content-of-list',array('title'=>'Soberanía Argentina','img'=>'/img/test/malvinas.jpg','url'=>'/economia/malvinas','txt'=>'Hoy se celebrará una reunión del Consejo OTAN-Rusia a nivel de embajadores. Hoy se celebrará una reunión del Consejo OTAN-Rusia a nivel de embajadores. Hoy se celebrará una reunión del Consejo OTAN-Rusia a nivel de embajadores. Hoy se celebrará una reunión del Consejo OTAN-Rusia a nivel de embajadores.'))
@include('front.articles.assets.content-of-list',array('title'=>'Soberanía Argentina','img'=>'/img/test/malvinas.jpg','url'=>'/economia/malvinas','txt'=>'Hoy se celebrará una reunión del Consejo OTAN-Rusia a nivel de embajadores. Hoy se celebrará una reunión del Consejo OTAN-Rusia a nivel de embajadores. Hoy se celebrará una reunión del Consejo OTAN-Rusia a nivel de embajadores. Hoy se celebrará una reunión del Consejo OTAN-Rusia a nivel de embajadores.'))
@include('front.articles.assets.content-of-list',array('title'=>'Soberanía Argentina','img'=>'/img/test/malvinas.jpg','url'=>'/economia/malvinas','txt'=>'Hoy se celebrará una reunión del Consejo OTAN-Rusia a nivel de embajadores. Hoy se celebrará una reunión del Consejo OTAN-Rusia a nivel de embajadores. Hoy se celebrará una reunión del Consejo OTAN-Rusia a nivel de embajadores. Hoy se celebrará una reunión del Consejo OTAN-Rusia a nivel de embajadores.'))
@include('front.articles.assets.content-of-list',array('title'=>'Soberanía Argentina','img'=>'/img/test/malvinas.jpg','url'=>'/economia/malvinas','txt'=>'Hoy se celebrará una reunión del Consejo OTAN-Rusia a nivel de embajadores. Hoy se celebrará una reunión del Consejo OTAN-Rusia a nivel de embajadores. Hoy se celebrará una reunión del Consejo OTAN-Rusia a nivel de embajadores. Hoy se celebrará una reunión del Consejo OTAN-Rusia a nivel de embajadores.'))
@include('front.articles.assets.content-of-list',array('title'=>'Soberanía Argentina','img'=>'/img/test/malvinas.jpg','url'=>'/economia/malvinas','txt'=>'Hoy se celebrará una reunión del Consejo OTAN-Rusia a nivel de embajadores. Hoy se celebrará una reunión del Consejo OTAN-Rusia a nivel de embajadores. Hoy se celebrará una reunión del Consejo OTAN-Rusia a nivel de embajadores. Hoy se celebrará una reunión del Consejo OTAN-Rusia a nivel de embajadores.'))

@endsection
